num_1 = int(input("Number 1 "))
num_2 = int(input("Number 2"))
print(num_1,"+", num_2,"=",num_1+num_2)
print(num_1,"-", num_2,"=",num_1-num_2)
print(num_1,"*", num_2,"=",num_1*num_2)
print(num_1,"/", num_2,"=",num_1/num_2)